import type { TranslationKey } from "./tr";

const en: Record<TranslationKey, string> = {
	// Navigation
	"tab.home": "Home",
	"tab.cabinet": "Cabinet",
	"tab.calendar": "Calendar",
	"tab.assistant": "Assistant",
	"tab.profile": "Profile",

	// Profile & Settings
	"profile.title": "Profile & Settings",
	"profile.accessibility": "Accessibility",
	"profile.highContrast": "High Contrast Mode",
	"profile.highContrastDesc": "Increase color contrast for better visibility",
	"profile.textSize": "Text Size",
	"profile.language": "Language",
	"profile.languageDesc": "App language",
	"profile.theme": "Theme",
	"profile.themeDesc": "App appearance",
	"profile.themeLight": "Light",
	"profile.themeDark": "Dark",
	"profile.themeSystem": "System",
	"profile.careTeam": "My Care Team",
	"profile.manageCaregivers": "Manage Caregivers",
	"profile.account": "Account",
	"profile.logout": "Log Out",
	"profile.loggingOut": "Logging Out...",

	// Add Medication Form
	"med.infoTitle": "Medication Details",
	"med.brandName": "Brand Name",
	"med.brandPlaceholder": "e.g. Parol, Augmentin",
	"med.genericName": "Generic Name",
	"med.genericPlaceholder": "e.g. Paracetamol",
	"med.genericOptional": "(optional)",
	"med.form": "Form",
	"med.dosage": "Dosage / Strength",
	"med.dosagePlaceholder": "e.g. 500 mg",
	"med.scheduleTitle": "Schedule",
	"med.doseCount": "Times per Day?",
	"med.mealStatus": "Meal Instructions",
	"med.mealBefore": "Before Meal",
	"med.mealAfter": "After Meal",
	"med.mealWith": "With Food",
	"med.mealAny": "Any Time",
	"med.frequency": "Frequency",
	"med.freqDaily": "Daily",
	"med.freqWeekly": "Weekly",
	"med.freqAsNeeded": "As Needed",
	"med.freqPeriodic": "Periodic",
	"med.reminderTimes": "Reminder Times",
	"med.addTime": "+ Add Time",
	"med.noTimes": "No times set. Tap \"+ Add Time\" to schedule reminders.",
	"med.stockTitle": "Inventory Tracking",
	"med.currentStock": "Current Stock",
	"med.alertLimit": "Alert Limit",
	"med.save": "Add Medication",
	"med.saveChanges": "Save Changes",
	"med.edit": "Edit Medication",
	"med.new": "New Medication",

	// AI Note Card
	"med.aiNote.title": "AI Medication Note",
	"med.aiNote.subtitle": "Auto-simplifies the drug prospectus",
	"med.aiNote.generate": "Generate AI Note",
	"med.aiNote.regenerate": "Regenerate",
	"med.aiNote.generating": "Generating AI Note...",
	"med.aiNote.label": "Notes",
	"med.aiNote.placeholder": "Tap the button above to generate a note...",
	"med.aiNote.disclaimer": "This note was generated by AI. Always consult your doctor or pharmacist.",
	"med.aiNote.noName": "Please enter a brand name or generic name first.",

	"validation.nameRequired": "Please enter a brand name or generic name.",
	"validation.dosageRequired": "Please fill in the dosage field.",
	"validation.error": "Error",

	// Dashboard
	"dashboard.greeting": "Good Morning",
	"dashboard.todaySchedule": "Today's Schedule",
	"dashboard.adherence": "Adherence Rate",
	"dashboard.nextDose": "Next Dose",
	"dashboard.noDoses": "No doses scheduled for today",

	// Meds Cabinet
	"cabinet.title": "My Cabinet",
	"cabinet.empty": "No medications added yet",
	"cabinet.addFirst": "Add your first medication",
	"cabinet.scanBox": "Scan Box",
	"cabinet.addManual": "Add Manually",
	"cabinet.selected": "Selected",
	"cabinet.deleteSelected": "Delete Selected",
	"cabinet.cancelSelection": "Cancel",

	// Calendar
	"calendar.title": "Calendar",
	"calendar.today": "Today",
	"calendar.noEvents": "No records for this day",

	// Scan
	"scan.title": "Scan Medication Box",
	"scan.instruction": "Point your camera at the medication box",
	"scan.analyzing": "Analyzing...",
	"scan.takePhoto": "Take Photo",
	"scan.retake": "Retake",
	"scan.useResult": "Use This Result",

	// Time Picker
	"timePicker.title": "Select Time",
	"timePicker.cancel": "Cancel",
	"timePicker.confirm": "Confirm",

	// Common
	"common.cancel": "Cancel",
	"common.confirm": "Confirm",
	"common.save": "Save",
	"common.delete": "Delete",
	"common.edit": "Edit",
	"common.loading": "Loading...",

	// Caregiver Activity Log
	"log.title": "Activity Log",
	"log.subtitle": "Recent actions by your patients",
	"log.empty": "No activity yet",
	"log.emptyDesc": "Activity from your patients will appear here",
	"log.statusTaken": "Took",
	"log.statusSkipped": "Skipped",
	"log.statusMissed": "Missed",
	"log.onTime": "On Time",
	"log.late": "Late",
	"log.today": "Today",
	"log.yesterday": "Yesterday",

	// Caregiver Dashboard
	"cg.dashboard": "Dashboard",
	"cg.managePatients": "Manage your patients",
	"cg.activePatients": "Active Patients",
	"cg.pendingAlerts": "Pending Alerts",
	"cg.invitePatient": "Invite Patient",
	"cg.inviteDesc": "Send an invitation via email",
	"cg.patientEmail": "Patient Email",
	"cg.sendInvite": "Send Invite",
	"cg.quickActions": "Quick Actions",
	"cg.viewAllPatients": "View All Patients",
	"cg.checkAlerts": "Check Alerts",
	"cg.allPatients": "All Patients",
	"cg.addMedication": "Add Medication",
	"cg.patientDetails": "Patient Details",
	"cg.medications": "Medications",
	"cg.noMedications": "No medications added yet",

	// Assistant
	"assistant.title": "Health Assistant",
	"assistant.welcomeMessage": "Hello! I can answer your questions about your medications. What would you like to know?",
	"assistant.inputPlaceholder": "Type your message...",
	"assistant.suggestion1": "\"Did I take my medicine today?\"",
	"assistant.suggestion2": "\"When is my next dose?\"",
	"assistant.suggestion3": "\"How is my medication stock?\"",
};

export default en;
